apiVersion: v1
kind: Pod
metadata:
  name: busybox-test-pod
spec:
  containers:
    - name: test-container
      image: registry.k8s.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: LOG_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: example-config
              # Specify the key associated with the value
              key: log.level
      volumes:
        - name: config
          configMap:
            name: example-config
          volumeMounts:
            - name: config
              mountPath: /etc/kconfig
              readOnly: true


      
  restartPolicy: Never