apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
  selector:
    app: flask
spec:
  template:
    metadata:
      labels:
         app: flask
    spec:
      containers:
      - name: flask
        image: quay.io/werstatyw/flask:0.1.1
        ports: 
        - containerPort: 5000