---
# EXPORT SERVICE INTERFACE
kind: Service
apiVersion: v1
metadata:
    name: flask-service-clusterip
spec:
  type: ClusterIP
  ports:
  - port: 5000
  selector:
      app: flask

---
---
# EXPORT SERVICE INTERFACE
kind: Service
apiVersion: v1
metadata:
    name: flask-service-lb
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
      app: flask
status:
  loadBalancer:
    ingress:
    - ip: 46.30.43.68

---
---
# EXPORT SERVICE INTERFACE
kind: Service
apiVersion: v1
metadata:
    name: flask-service-nodeport
spec:
  type: NodePort
  ports:
  - port: 5000
  selector:
      app: flask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    run: flask
spec:
  selector:
    matchLabels:
        app: flask
  template:
    metadata:
      labels:
         app: flask
    spec:
      containers:
      - name: flask
        image: quay.io/kubernetes-for-developers/flask:0.2.0
        ports:
        - containerPort: 5000
